//
// Created by fuwei on 25-3-7.
//

#ifndef TPM2_PKCS_H
#define TPM2_PKCS_H

#include <stdbool.h>
#include <stdint.h>

#define ck_key_type_t CK_KEY_TYPE
typedef unsigned long ck_key_type_t;

#define ck_object_handle_t CK_OBJECT_HANDLE;
typedef unsigned long ck_object_handle_t;

#define CKF_LIBRARY_CANT_CREATE_OS_THREADS (1UL << 0)
#define CKF_OS_LOCKING_OK (1UL << 1)

typedef unsigned char CK_BYTE;
typedef unsigned char CK_CHAR;
typedef unsigned long int CK_ULONG;
typedef long int CK_LONG;

typedef CK_BYTE* CK_BYTE_PTR;
typedef CK_CHAR* CK_CHAR_PTR;
typedef CK_ULONG* CK_ULONG_PTR;
// error
#define CKR_OK (0UL)
#define CKR_CANCEL (1UL)
#define CKR_HOST_MEMORY (2UL)
#define CKR_SLOT_ID_INVALID (3UL)
#define CKR_GENERAL_ERROR (5UL)
#define CKR_FUNCTION_FAILED (6UL)
#define CKR_ARGUMENTS_BAD (7UL)
#define CKR_NO_EVENT (8UL)
#define CKR_NEED_TO_CREATE_THREADS (9UL)
#define CKR_CANT_LOCK (0xaUL)
#define CKR_ATTRIBUTE_READ_ONLY (0x10UL)
#define CKR_ATTRIBUTE_SENSITIVE (0x11UL)
#define CKR_ATTRIBUTE_TYPE_INVALID (0x12UL)
#define CKR_ATTRIBUTE_VALUE_INVALID (0x13UL)
#define CKR_ACTION_PROHIBITED (0x1BUL)
#define CKR_DATA_INVALID (0x20UL)
#define CKR_DATA_LEN_RANGE (0x21UL)
#define CKR_DEVICE_ERROR (0x30UL)
#define CKR_DEVICE_MEMORY (0x31UL)
#define CKR_DEVICE_REMOVED (0x32UL)
#define CKR_ENCRYPTED_DATA_INVALID (0x40UL)
#define CKR_ENCRYPTED_DATA_LEN_RANGE (0x41UL)
#define CKR_FUNCTION_CANCELED (0x50UL)
#define CKR_FUNCTION_NOT_PARALLEL (0x51UL)
#define CKR_FUNCTION_NOT_SUPPORTED (0x54UL)
#define CKR_KEY_HANDLE_INVALID (0x60UL)
#define CKR_KEY_SIZE_RANGE (0x62UL)
#define CKR_KEY_TYPE_INCONSISTENT (0x63UL)
#define CKR_KEY_NOT_NEEDED (0x64UL)
#define CKR_KEY_CHANGED (0x65UL)
#define CKR_KEY_NEEDED (0x66UL)
#define CKR_KEY_INDIGESTIBLE (0x67UL)
#define CKR_KEY_FUNCTION_NOT_PERMITTED (0x68UL)
#define CKR_KEY_NOT_WRAPPABLE (0x69UL)
#define CKR_KEY_UNEXTRACTABLE (0x6aUL)
#define CKR_MECHANISM_INVALID (0x70UL)
#define CKR_MECHANISM_PARAM_INVALID (0x71UL)
#define CKR_OBJECT_HANDLE_INVALID (0x82UL)
#define CKR_OPERATION_ACTIVE (0x90UL)
#define CKR_OPERATION_NOT_INITIALIZED (0x91UL)
#define CKR_PIN_INCORRECT (0xa0UL)
#define CKR_PIN_INVALID (0xa1UL)
#define CKR_PIN_LEN_RANGE (0xa2UL)
#define CKR_PIN_EXPIRED (0xa3UL)
#define CKR_PIN_LOCKED (0xa4UL)
#define CKR_SESSION_CLOSED (0xb0UL)
#define CKR_SESSION_COUNT (0xb1UL)
#define CKR_SESSION_HANDLE_INVALID (0xb3UL)
#define CKR_SESSION_PARALLEL_NOT_SUPPORTED (0xb4UL)
#define CKR_SESSION_READ_ONLY (0xb5UL)
#define CKR_SESSION_EXISTS (0xb6UL)
#define CKR_SESSION_READ_ONLY_EXISTS (0xb7UL)
#define CKR_SESSION_READ_WRITE_SO_EXISTS (0xb8UL)
#define CKR_SIGNATURE_INVALID (0xc0UL)
#define CKR_SIGNATURE_LEN_RANGE (0xc1UL)
#define CKR_TEMPLATE_INCOMPLETE (0xd0UL)
#define CKR_TEMPLATE_INCONSISTENT (0xd1UL)
#define CKR_TOKEN_NOT_PRESENT (0xe0UL)
#define CKR_TOKEN_NOT_RECOGNIZED (0xe1UL)
#define CKR_TOKEN_WRITE_PROTECTED (0xe2UL)
#define CKR_UNWRAPPING_KEY_HANDLE_INVALID (0xf0UL)
#define CKR_UNWRAPPING_KEY_SIZE_RANGE (0xf1UL)
#define CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT (0xf2UL)
#define CKR_USER_ALREADY_LOGGED_IN (0x100UL)
#define CKR_USER_NOT_LOGGED_IN (0x101UL)
#define CKR_USER_PIN_NOT_INITIALIZED (0x102UL)
#define CKR_USER_TYPE_INVALID (0x103UL)
#define CKR_USER_ANOTHER_ALREADY_LOGGED_IN (0x104UL)
#define CKR_USER_TOO_MANY_TYPES (0x105UL)
#define CKR_WRAPPED_KEY_INVALID (0x110UL)
#define CKR_WRAPPED_KEY_LEN_RANGE (0x112UL)
#define CKR_WRAPPING_KEY_HANDLE_INVALID (0x113UL)
#define CKR_WRAPPING_KEY_SIZE_RANGE (0x114UL)
#define CKR_WRAPPING_KEY_TYPE_INCONSISTENT (0x115UL)
#define CKR_RANDOM_SEED_NOT_SUPPORTED (0x120UL)
#define CKR_RANDOM_NO_RNG (0x121UL)
#define CKR_DOMAIN_PARAMS_INVALID (0x130UL)
#define CKR_CURVE_NOT_SUPPORTED (0x140UL)
#define CKR_BUFFER_TOO_SMALL (0x150UL)
#define CKR_SAVED_STATE_INVALID (0x160UL)
#define CKR_INFORMATION_SENSITIVE (0x170UL)
#define CKR_STATE_UNSAVEABLE (0x180UL)
#define CKR_CRYPTOKI_NOT_INITIALIZED (0x190UL)
#define CKR_CRYPTOKI_ALREADY_INITIALIZED (0x191UL)
#define CKR_MUTEX_BAD (0x1a0UL)
#define CKR_MUTEX_NOT_LOCKED (0x1a1UL)
#define CKR_NEW_PIN_MODE (0x1b0UL)
#define CKR_NEXT_OTP (0x1b1UL)
#define CKR_EXCEEDED_MAX_ITERATIONS (0x1c0UL)
#define CKR_FIPS_SELF_TEST_FAILED (0x1c1UL)
#define CKR_LIBRARY_LOAD_FAILED (0x1c2UL)
#define CKR_PIN_TOO_WEAK (0x1c3UL)
#define CKR_PUBLIC_KEY_INVALID (0x1c4UL)
#define CKR_FUNCTION_REJECTED (0x200UL)
#define CKR_VENDOR_DEFINED ((unsigned long)(1UL << 31))

#endif  //TPM2_PKCS_H
